package com.model;

/**
 * TLivi generated by MyEclipse Persistence Tools
 * 实体类，一般一个数据库表对应一个实体类，将表中的一条记录用实体类包装，通过get/set方法获取与设置
 * 对应了t_lilv这张表，里面的字段就对应了实体类的成员变量
 */
public class TLilv implements java.io.Serializable
{

	// Fields
	//记录id
	private Integer id;
	//利率
	private Double lilv;

	// Constructors

	/** default constructor */
	public TLilv()
	{
	}

	/** full constructor */
	public TLilv(Double lilv)
	{
		this.lilv = lilv;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Double getLilv()
	{
		return this.lilv;
	}

	public void setLilv(Double lilv)
	{
		this.lilv = lilv;
	}

}