package com.model;

/**
 * TQu generated by MyEclipse Persistence Tools
 */

public class TQu implements java.io.Serializable
{

	private Integer id;
	private Integer userId;
	private Integer jine;
	private String shijian;
	
	
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public Integer getJine()
	{
		return jine;
	}
	public void setJine(Integer jine)
	{
		this.jine = jine;
	}
	public String getShijian()
	{
		return shijian;
	}
	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}
	public Integer getUserId()
	{
		return userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}
	
}