package com.model;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable
{

	private Integer id;
	private String realname;
	private String sex;
	private String age;

	private String address;
	private String tel;
	private String email;
	private String kahao;

	private String ps;
	private String shenfenzheng;
	private Integer yue;

	private String tai;//×´Ì¬£¬¶³½á----Õý³£---É¾³ý

	public String getAddress()
	{
		return address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	public String getAge()
	{
		return age;
	}

	public void setAge(String age)
	{
		this.age = age;
	}

	public String getEmail()
	{
		return email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getKahao()
	{
		return kahao;
	}

	public void setKahao(String kahao)
	{
		this.kahao = kahao;
	}

	public String getPs()
	{
		return ps;
	}

	public void setPs(String ps)
	{
		this.ps = ps;
	}

	public String getRealname()
	{
		return realname;
	}

	public void setRealname(String realname)
	{
		this.realname = realname;
	}

	public String getSex()
	{
		return sex;
	}

	public void setSex(String sex)
	{
		this.sex = sex;
	}

	public String getShenfenzheng()
	{
		return shenfenzheng;
	}

	public void setShenfenzheng(String shenfenzheng)
	{
		this.shenfenzheng = shenfenzheng;
	}

	public String getTai()
	{
		return tai;
	}

	public void setTai(String tai)
	{
		this.tai = tai;
	}

	public String getTel()
	{
		return tel;
	}

	public void setTel(String tel)
	{
		this.tel = tel;
	}

	public Integer getYue()
	{
		return yue;
	}

	public void setYue(Integer yue)
	{
		this.yue = yue;
	}

}