package com.model;

/**
 * TUser generated by MyEclipse Persistence Tools
 * 实体类，一般一个数据库表对应一个实体类，将表中的一条记录用实体类包装，通过get/set方法获取与设置
 * 对应了t_user这张表，里面的字段就对应了实体类的成员变量
 */
public class TUser implements java.io.Serializable
{
	//用户id
	private Integer id;
	//真实姓名
	private String realname;
	//性别
	private String sex;
	//年龄
	private String age;
	//地址
	private String address;
	//电话号码
	private String tel;
	//电子邮箱
	private String email;
	//银行卡号
	private String kahao;
	//账号密码
	private String ps;
	//身份证号码
	private String shenfenzheng;
	//账户余额
	private Integer yue;
	//银行卡状态
	private String tai;//状态，冻结----正常---删除

	public String getAddress()
	{
		return address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	public String getAge()
	{
		return age;
	}

	public void setAge(String age)
	{
		this.age = age;
	}

	public String getEmail()
	{
		return email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getKahao()
	{
		return kahao;
	}

	public void setKahao(String kahao)
	{
		this.kahao = kahao;
	}

	public String getPs()
	{
		return ps;
	}

	public void setPs(String ps)
	{
		this.ps = ps;
	}

	public String getRealname()
	{
		return realname;
	}

	public void setRealname(String realname)
	{
		this.realname = realname;
	}

	public String getSex()
	{
		return sex;
	}

	public void setSex(String sex)
	{
		this.sex = sex;
	}

	public String getShenfenzheng()
	{
		return shenfenzheng;
	}

	public void setShenfenzheng(String shenfenzheng)
	{
		this.shenfenzheng = shenfenzheng;
	}

	public String getTai()
	{
		return tai;
	}

	public void setTai(String tai)
	{
		this.tai = tai;
	}

	public String getTel()
	{
		return tel;
	}

	public void setTel(String tel)
	{
		this.tel = tel;
	}

	public Integer getYue()
	{
		return yue;
	}

	public void setYue(Integer yue)
	{
		this.yue = yue;
	}

}