package com.model;

/**
 * TZhuanzhang generated by MyEclipse Persistence Tools
 * 实体类，一般一个数据库表对应一个实体类，将表中的一条记录用实体类包装，通过get/set方法获取与设置
 * 对应了t_zhuanzhang这张表，里面的字段就对应了实体类的成员变量
 */
public class TZhuanzhang implements java.io.Serializable
{
	//记录id
	private Integer id;
	//转账用户id
	private Integer fromUserId;
	//接收转账用户id
	private Integer toUserId;
	//转账金额
	private Integer jine;
	//转账时间
	private String shijian;
	//接收转账用户
	private TUser toUser;

	public Integer getFromUserId()
	{
		return fromUserId;
	}

	public void setFromUserId(Integer fromUserId)
	{
		this.fromUserId = fromUserId;
	}

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getJine()
	{
		return jine;
	}

	public void setJine(Integer jine)
	{
		this.jine = jine;
	}

	public String getShijian()
	{
		return shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public TUser getToUser()
	{
		return toUser;
	}

	public void setToUser(TUser toUser)
	{
		this.toUser = toUser;
	}

	public Integer getToUserId()
	{
		return toUserId;
	}

	public void setToUserId(Integer toUserId)
	{
		this.toUserId = toUserId;
	}

}