package com.model;

/**
 * TZhuanzhang generated by MyEclipse Persistence Tools
 */

public class TZhuanzhang implements java.io.Serializable
{

	private Integer id;
	private Integer fromUserId;
	private Integer toUserId;
	private Integer jine;

	private String shijian;
	
	private TUser toUser;

	public Integer getFromUserId()
	{
		return fromUserId;
	}

	public void setFromUserId(Integer fromUserId)
	{
		this.fromUserId = fromUserId;
	}

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getJine()
	{
		return jine;
	}

	public void setJine(Integer jine)
	{
		this.jine = jine;
	}

	public String getShijian()
	{
		return shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public TUser getToUser()
	{
		return toUser;
	}

	public void setToUser(TUser toUser)
	{
		this.toUser = toUser;
	}

	public Integer getToUserId()
	{
		return toUserId;
	}

	public void setToUserId(Integer toUserId)
	{
		this.toUserId = toUserId;
	}

}